#include "unity/fixture/unity_fixture.h"

TEST_GROUP_RUNNER(observer_subscribe)
{
    RUN_TEST_CASE(observer_subscribe, GivenSubscriptionTableEmptyWhenSubscribeMockFun1ToSubscriptionTableThenFirstElementOfSubscriptionTableIsEqualToMockFun1AndRestElementsAreEmpty);
    RUN_TEST_CASE(observer_subscribe, GivenSubscriptionTableEmptyWhenSubscribeMockFun1AndNextSubscribedMockFun2ToSubscriptionTableThenInElemnt0IsEqualMockFun1AdresElement1IsEqualMockFun2AdrAndRestElementsAreEmpty);
    RUN_TEST_CASE(observer_subscribe, GivenSubscriptionTableEmptyWhenSubscribe3functionsThenFirst3CllbackTableElementsAreEqualToFunctionAdresssesAccordingToRegistrationOrderAndRestAreEqualNull);
    RUN_TEST_CASE(observer_subscribe, GivenSubscriptionTableEmptyWhenSubscribeMockFun1ToSubscriptionTableThreeTimesThenFirstElementOfSubscriptionTableIsEqualToMockFun1AndRestElementsAreEmpty);

    /* SUBSCRIBE RET VALUE test cases to run */
    RUN_TEST_CASE(observer_subscribe, GivenSubscriptionTableFullWhenSubscribeMockFun1ToSubscriptionTableThenFunctionReturnSubscriptionTableFullStatus);
    RUN_TEST_CASE(observer_subscribe, WhenSubscribeMockFun1ToSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToObserverOk);
    RUN_TEST_CASE(observer_subscribe, WhenSubscribeMockFun1ToSubscriptionTableWith0LenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
    RUN_TEST_CASE(observer_subscribe, WhenSubscribeNullToSubscriptionTableWithWitnNonZeroLenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
    RUN_TEST_CASE(observer_subscribe, WhenSubscribeMockFun1ToNullPtrSubscriptionTableWitnNonZeroLenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
}

TEST_GROUP_RUNNER(observer_subscribe_with_state_arg)
{
    RUN_TEST_CASE(observer_subscribe_with_state_arg, GivenSubscriptionTableEmptyWhenSubscribeMockFun1ThenFirstElementEqualsMockFun1AndRestAreEmpty);
    RUN_TEST_CASE(observer_subscribe_with_state_arg, GivenSubscriptionTableEmptyWhenSubscribeMockFun1ThenMockFun2ThenCorrectOrderInTable);
    RUN_TEST_CASE(observer_subscribe_with_state_arg, GivenSubscriptionTableEmptyWhenSubscribe3FunctionsThenFirst3ElementsSetAccordingToOrder);
    RUN_TEST_CASE(observer_subscribe_with_state_arg, GivenEmptyTableWhenSubscribeSameCallback3TimesThenOnlyFirstSlotIsFilled);

    /* SUBSCRIBE RET VALUE test cases to run */
    RUN_TEST_CASE(observer_subscribe_with_state_arg, GivenFullTableWhenSubscribeAnotherCallbackThenReturnTableFullError);
    RUN_TEST_CASE(observer_subscribe_with_state_arg, WhenSubscribeStateChangeMockFun1ToSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToObserverOk);
    RUN_TEST_CASE(observer_subscribe_with_state_arg, WhenSubscribeStateChangeMockFun1ToSubscriptionTableWith0LenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
    RUN_TEST_CASE(observer_subscribe_with_state_arg, WhenSubscribeStateChangeNullToSubscriptionTableWithWitnNonZeroLenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
    RUN_TEST_CASE(observer_subscribe_with_state_arg, WhenSubscribeStateChangeMockFun1ToNullPtrSubscriptionTableWitnNonZeroLenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
}

TEST_GROUP_RUNNER(observer_subscribe_with_u8_arg)
{
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, GivenSubscriptionTableEmptyWhenSubscribeMockFun1ThenFirstElementEqualsMockFun1AndRestAreEmpty);
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, GivenSubscriptionTableEmptyWhenSubscribeMockFun1ThenMockFun2ThenCorrectOrderInTable);
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, GivenSubscriptionTableEmptyWhenSubscribe3FunctionsThenFirst3ElementsSetAccordingToOrder);
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, GivenEmptyTableWhenSubscribeSameCallback3TimesThenOnlyFirstSlotIsFilled);

    /* SUBSCRIBE RET VALUE test cases to run */
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, GivenFullTableWhenSubscribeAnotherCallbackThenReturnTableFullError);
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, WhenSubscribeU8MockFun1ToSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToObserverOk);
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, WhenSubscribeU8MockFun1ToSubscriptionTableWith0LenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, WhenSubscribeU8NullToSubscriptionTableWithWitnNonZeroLenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
    RUN_TEST_CASE(observer_subscribe_with_u8_arg, WhenSubscribeU8MockFun1ToNullPtrSubscriptionTableWitnNonZeroLenghtThenReturnedValueIsEqualToCallbackErrorInvalidArgument);
}

TEST_GROUP_RUNNER(observer_unsubscribe)
{
    RUN_TEST_CASE(observer_unsubscribe, GivenMocFun1FuncionSubscribedWhenMockFun1UnsubscribeThenSubscribtionTableEqualToExpected);
    RUN_TEST_CASE(observer_unsubscribe, GivenMocFun1ToMockFun5FuncionSubscribedWhenUnsubscribeMockFun3FunnctionCalledThenSubscribtionTableEqualToExpected);
    RUN_TEST_CASE(observer_unsubscribe, GivenMocFun1ToMockFun5FuncionSubscribedWhenUnsubscribeMockFun5FunnctionCalledThenSubscribtionTableEqualToExpected);

    RUN_TEST_CASE(observer_unsubscribe, GivenSubscribtionTableFullWhenUnsubscribeOneBeforeLastFunctionThenSubscribtionTableEqualToExpected);
    RUN_TEST_CASE(observer_unsubscribe, GivenSubscribtionTableFullWhenUnsubscribe5thFunctionInCallbackTableThenSubscribtionTableEqualToExpected);
    RUN_TEST_CASE(observer_unsubscribe, GivenSubscribtionTableFullWhenUnsubscribeLastFunctionThenSubscribtionTableEqualToExpected);

    RUN_TEST_CASE(observer_unsubscribe, GivenSubscribtionTableWithLastElementEqualNullWhenUnsubscribeOneBeforeLastSubscribedFunctionThenSubscribtionTableEqualToExpected);
    RUN_TEST_CASE(observer_unsubscribe, GivenSubscribtionTableWithLastElementEqualNullWhenUnsubscribe5thSubscribedFunctionThenSubscribtionTableEqualToExpected);
    RUN_TEST_CASE(observer_unsubscribe, GivenSubscribtionTableWithLastElementEqualNullWhenUnsubscribeLastSubscribedFunctionThenSubscribtionTableEqualToExpected);

    RUN_TEST_CASE(observer_unsubscribe, GivenSubscribtionTableFullWithMock1FunAdressesWhenMock1FunUnsubscribedThenSubscriptionTableIsEmpty);

    /* SUBSCRIBE RET VALUE test cases to run */
    RUN_TEST_CASE(observer_unsubscribe, GivenSubscriptionTableEmptyWhenUnsubscribeMockFun1FromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToCallbackNotFoundError);
    RUN_TEST_CASE(observer_unsubscribe, GivenMocFun1FuncionSubscribedWhenUnsubscribeMockFun1FromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToObserverOk);
    RUN_TEST_CASE(observer_unsubscribe, GivenMocFun1FuncionSubscribedWhenUnsubscribeMockFun1FromSubscriptionTableWitZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
    RUN_TEST_CASE(observer_unsubscribe, GivenMocFun1FuncionSubscribedWhenUnsubscribeNullPtrFromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
    RUN_TEST_CASE(observer_unsubscribe, GivenMocFun1FuncionSubscribedWhenUnsubscribeMockFun1FromNullPtrSubscrTableWitnNonZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
}

TEST_GROUP_RUNNER(observer_unsubscribe_with_state_arg)
{
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenDummyCbSubscribedWhenUnsubThenTableIsEmpty);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenFun1To5SubscribedWhenUnsubFun3ThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenFun1To5SubscribedWhenUnsubFun5ThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenTableFullWhenUnsubOneBeforeLastThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenTableFullWhenUnsub5thElementThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenTableFullWhenUnsubLastElementThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenTableWithLastNullWhenUnsubOneBeforeLastThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenTableWithLastNullWhenUnsub5thFunctionThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenTableWithLastNullWhenUnsubLastSubscribedThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenTableFullOfSameFunWhenUnsubThenTableIsEmpty);

    /* SUBSCRIBE RET VALUE test cases to run */
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenSubscriptionTableEmptyWhenUnsubscribeStateChangeDummyCbFromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToCallbackNotFoundError);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenMocFun1FuncionSubscribedWhenUnsubscribeStateChangeDummyCbFromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToObserverOk);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenMocFun1FuncionSubscribedWhenUnsubscribeStateChangeDummyCbFromSubscriptionTableWitZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenMocFun1FuncionSubscribedWhenUnsubscribeStateChangeNullPtrFromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
    RUN_TEST_CASE(observer_unsubscribe_with_state_arg, GivenMocFun1FuncionSubscribedWhenUnsubscribeStateChangeDummyCbFromNullPtrSubscrTableWitnNonZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
}

TEST_GROUP_RUNNER(observer_unsubscribe_with_u8_arg)
{
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenDummyCbSubscribedWhenUnsubThenTableIsEmpty);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenFun1To5SubscribedWhenUnsubFun3ThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenFun1To5SubscribedWhenUnsubFun5ThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenTableFullWhenUnsubOneBeforeLastThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenTableFullWhenUnsub5thElementThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenTableFullWhenUnsubLastElementThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenTableWithLastNullWhenUnsubOneBeforeLastThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenTableWithLastNullWhenUnsub5thFunctionThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenTableWithLastNullWhenUnsubLastSubscribedThenTableEqualExpected);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenTableFullOfSameFunWhenUnsubThenTableIsEmpty);

    /* SUBSCRIBE RET VALUE test cases to run */
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenSubscriptionTableEmptyWhenUnsubscribeU8DummyCbFromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToCallbackNotFoundError);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenMocFun1FuncionSubscribedWhenUnsubscribeU8DummyCbFromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToCalbbackSubscrOk);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenMocFun1FuncionSubscribedWhenUnsubscribeU8DummyCbFromSubscriptionTableWitZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenMocFun1FuncionSubscribedWhenUnsubscribeU8NullPtrFromSubscriptionTableWitnNonZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
    RUN_TEST_CASE(observer_unsubscribe_with_u8_arg, GivenMocFun1FuncionSubscribedWhenUnsubscribeU8DummyCbFromNullPtrSubscrTableWitnNonZeroLenghtThenRetValueIsEqualToCalbbackSubscrErrorInvalidArgument);
}

TEST_GROUP_RUNNER(observer_notify)
{
    RUN_TEST_CASE(observer_notify, GivenMockFunCountersResetedAndMockFun1MockFun2MockFun3SubscribedWhenNotifyCalledThenSubscribedMockFunCountersEqual1);
    RUN_TEST_CASE(observer_notify, GivenMockFunCountersResetedAndMockFun1MockFun2MockFun3SubscribedAndNotifyCalledAndMock2FunUnsubscribedWhenNotifyCalledThenSubscribedMockFun1AndMockFun3CountersEqual2AndMockFun2CounterEqual1);

    /* SUBSCRIBE RET VALUE test cases to run */
    RUN_TEST_CASE(observer_notify, GivenMockFun1MockFun2MockFun3SubscribedWhenNotifyCalledWithSubscrCallbackTablePtrAndNonZeroSubscrTableLenThenRetValueEqualObserverOk);
    RUN_TEST_CASE(observer_notify, GivenMockFun1MockFun2MockFun3SubscribedWhenNotifyCalledWithNullPtrAndNonZeroSubscrTableLenThenRetValueEqualObserverOk);
    RUN_TEST_CASE(observer_notify, GivenMockFun1MockFun2MockFun3SubscribedWhenNotifyCalledWithSubscrCallbackTablePtrAndSubscrTableLenEqual0ThenRetValueEqualObserverOk);
    RUN_TEST_CASE(observer_notify, GivenSubscriptionTableEmptyWhenNotifyCalledWithSubscrCallbackTablePtrAndNonZeroSubscrTableLenThenRetValueEqualObserverTableEmptyError);
}

TEST_GROUP_RUNNER(observer_notify_with_state_arg)
{
    RUN_TEST_CASE(observer_notify_with_state_arg, GivenMockCountersResetedAndAll3SubscribedWhenNotifyWithStateArgCalledThenEachCounterIncreased);
    RUN_TEST_CASE(observer_notify_with_state_arg, GivenAll3SubscribedAndOneUnsubscribedWhenNotifyWithStateArgCalledThenOnlyRemainingAreNotified);

    // /* SUBSCRIBE RET VALUE test cases to run */
    RUN_TEST_CASE(observer_notify_with_state_arg, GivenMockFun1MockFun2MockFun3SubscribedWhenNotifyWithStateCalledWithSubscrCallbackTablePtrAndNonZeroSubscrTableLenThenRetValueEqualObserverOk);
    RUN_TEST_CASE(observer_notify_with_state_arg, GivenMockFun1MockFun2MockFun3SubscribedWhenNotifyWithStateCalledWithNullPtrAndNonZeroSubscrTableLenThenRetValueEqualObserverOk);
    RUN_TEST_CASE(observer_notify_with_state_arg, GivenMockFun1MockFun2MockFun3SubscribedWhenNotifyWithStateCalledWithSubscrCallbackTablePtrAndSubscrTableLenEqual0ThenRetValueEqualObserverOk);
    RUN_TEST_CASE(observer_notify_with_state_arg, GivenSubscriptionTableEmptyWhenNotifyWithStateCalledWithSubscrCallbackTablePtrAndNonZeroSubscrTableLenThenRetValueEqualObserverTableEmptyError);
}

TEST_GROUP_RUNNER(observer_notify_with_u8_arg)
{
    RUN_TEST_CASE(observer_notify_with_u8_arg, GivenMockCountersResetedAndAll3SubscribedWhenNotifyWithArgCalledThenEachCounterIncreased);
    RUN_TEST_CASE(observer_notify_with_u8_arg, GivenAll3SubscribedAndOneUnsubscribedWhenNotifyWithArgCalledThenOnlyRemainingAreNotified);
}